// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-VxUE-wnQoLK-52s3T6SeOf_SjnmyUa8',
    appId: '1:102761528779:android:084a4788cab352b7640a4e',
    messagingSenderId: '102761528779',
    projectId: 'epilepsy-b452b',
    storageBucket: 'epilepsy-b452b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3M53XRg3g8pgTPx1RjcezSUpYGQmLoY',
    appId: '1:102761528779:ios:0900c2b776715eca640a4e',
    messagingSenderId: '102761528779',
    projectId: 'epilepsy-b452b',
    storageBucket: 'epilepsy-b452b.appspot.com',
    androidClientId: '102761528779-jg41ktvgp9p9bp6l0rr1788p1pvvuebk.apps.googleusercontent.com',
    iosClientId: '102761528779-4tk6qgd3jcrks0ifk7c6ui2nq67bf6ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.epilepsyApp',
  );
}
